version: '3.7'
services:
  mongo:    
    container_name: mongodb
    image: mongo:3.6
    restart: always
    ports:
      - "27017:27017" 
    environment:
      MONGO_INITDB_DATABASE: nab-test
      # MONGO_INITDB_ROOT_USERNAME: transybao
      # MONGO_INITDB_ROOT_PASSWORD: transybao
    networks:
      - bao_network
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: on-failure
    ports:
      - 8082:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=transybao
      - ME_CONFIG_MONGODB_ADMINPASSWORD=transybao
    links:
      - mongo
    networks:
      - bao_network
  nodejs:
    container_name: nodejs_api
    build:
      context: .
      dockerfile: nodejs.dockerfile
    restart: on-failure
    volumes:
      - .:/api
    environment: 
      - "NODE_ENV=development"
    ports:
      - 8001:8001
    links:
      - mongo
    networks:
      - bao_network
  nginx:
    container_name: nginx_reverse_proxy
    build:
      context: .
      dockerfile: nginx.dockerfile
    volumes:
      - ./nginx-conf/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    depends_on:
      - nodejs
    networks:
      - bao_network
    restart: on-failure
networks:
  bao_network:
    #driver: bridge
    external:
      name: bao_network
